package com.jucius.cesium.kafka.app.metrics;

import java.io.IOException;
import java.io.InputStream;
import java.util.Optional;
import java.util.Properties;

/**
 * Build provenance for the {@code /info} endpoint (design §9): the application version and, when
 * available, the short git commit. Loaded from the {@code cesium-build-info.properties} classpath
 * resource generated by the {@code generateBuildInfo} Gradle task; absent that (or git), it falls
 * back to the jar manifest's {@code Implementation-Version}, then to {@code "unknown"} — so {@code
 * /info} always answers.
 *
 * @param version the application version (Gradle project version, or manifest, or {@code "unknown"})
 * @param gitCommit the short git commit, or empty when the build did not record one
 */
public record BuildInfo(String version, Optional<String> gitCommit) {

    private static final String RESOURCE = "/cesium-build-info.properties";

    /** Loads build provenance from the classpath, applying the documented fallbacks. */
    public static BuildInfo load() {
        try (InputStream in = BuildInfo.class.getResourceAsStream(RESOURCE)) {
            if (in != null) {
                Properties props = new Properties();
                props.load(in);
                String version = props.getProperty("version", "");
                String commit = props.getProperty("gitCommit", "");
                return new BuildInfo(
                        version.isBlank() ? fallbackVersion() : version,
                        commit.isBlank() ? Optional.empty() : Optional.of(commit));
            }
        } catch (IOException ignored) {
            // Fall through to the manifest/unknown fallback below.
        }
        return new BuildInfo(fallbackVersion(), Optional.empty());
    }

    private static String fallbackVersion() {
        Package pkg = BuildInfo.class.getPackage();
        String manifestVersion = pkg == null ? null : pkg.getImplementationVersion();
        return manifestVersion == null ? "unknown" : manifestVersion;
    }
}
