package com.jucius.cesium.kafka.app.metrics;

import java.io.IOException;
import java.io.InputStream;
import java.util.Optional;
import java.util.Properties;

/**
 * Build provenance for the {@code /info} endpoint (design §9): the application version and, when
 * available, the short git commit. Loaded from the {@code cesium-build-info.properties} classpath
 * resource generated by the {@code generateBuildInfo} Gradle task; absent that it falls back to
 * {@code "unknown"} (and no commit when git was absent) — so {@code /info} always answers.
 *
 * @param version the application version (Gradle project version, or {@code "unknown"})
 * @param gitCommit the short git commit, or empty when the build did not record one
 */
public record BuildInfo(String version, Optional<String> gitCommit) {

    private static final String RESOURCE = "/cesium-build-info.properties";
    private static final String UNKNOWN = "unknown";

    /** Loads build provenance from the classpath, applying the documented fallbacks. */
    public static BuildInfo load() {
        try (InputStream in = BuildInfo.class.getResourceAsStream(RESOURCE)) {
            if (in != null) {
                Properties props = new Properties();
                props.load(in);
                String version = props.getProperty("version", "");
                String commit = props.getProperty("gitCommit", "");
                return new BuildInfo(
                        version.isBlank() ? UNKNOWN : version,
                        commit.isBlank() ? Optional.empty() : Optional.of(commit));
            }
        } catch (IOException ignored) {
            // Fall through to the "unknown" fallback below.
        }
        return new BuildInfo(UNKNOWN, Optional.empty());
    }
}
